Feat: List test run results with expandable rows for spec runs
Guidewire/fern-ui pull request #1
Opened 2024-05-20 04:48 UTC by gowtham-ra

1. List test run results with expandable rows for spec runs.
2. Add interfaces for TestRun, SpecRun and SuiteRun data models.
3. Update README.

2024-06-01 13:33 UTC, anoop2811 commented on src/App.tsx
Can we add tests?

2024-06-01 13:33 UTC, anoop2811 commented on src/pages/test-runs/list.tsx
Tests?

2024-06-01 13:34 UTC, anoop2811 requested changes
Can we add tests (acceptance at minimum)

2024-06-03 09:03 UTC, gowtham-ra commented on src/pages/test-runs/list.tsx
Added unit tests.

2024-06-14 03:09 UTC, anoop2811 commented on src/pages/test-runs/interfaces.ts
Prefixing `I` to interfaces  seems to be a very old pattern and mostly a microsoft pattern. Its better to use a proper nouns without the `I`.  Again, not an typescript expert, was going based off of what typescript authors were doing: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
https://stackoverflow.com/questions/68503504/what-is-the-naming-convention-for-interfaces-and-classes-in-typescript

2024-06-14 03:10 UTC, anoop2811 commented on src/pages/test-runs/interfaces.ts
https://aykhanhuseyn.medium.com/typescript-naming-conventions-crafting-maintainable-code-7d872234fe17

2024-06-14 04:11 UTC, gowtham-ra commented on src/pages/test-runs/interfaces.ts
I went with what refine used for interfaces in their [examples](https://github.com/refinedev/refine/blob/master/examples/search/src/interfaces/index.d.ts#L1). I didn't know it was from an old pattern. Thanks for the suggestion anyway. I'll change it to what's appropriate.

2024-06-14 22:41 UTC, fvarg00 commented on src/pages/test-runs/list.tsx
@gowtham-ra , can we include coverage after jest runs? We would need to add --coverage flag.

`    "test": "jest --coverage"`

I added it locally and ran the tests. It looks like show.tsx is missing coverage for lines 16-29. See screenshot below.

![image](https://github.com/Guidewire/fern-ui/assets/3069588/8eefb9d3-0be9-411d-990a-98d23a63432f)

2024-06-14 22:54 UTC, gowtham-ra commented on src/pages/test-runs/list.tsx
Hey @fvarg00, Sure thing. I'll add test coverage flag and also tests for the missing ones. Thanks.

2024-06-18 05:14 UTC, gowtham-ra commented on src/pages/test-runs/list.tsx
I removed the show page since it was an experimental page taken from the refine and isn't fully functional.

<img width="705" alt="Screenshot 2024-06-17 at 10 11 45 PM" src="https://github.com/Guidewire/fern-ui/assets/45856103/13a877d0-5b07-41fc-8e58-0683e56d9cdd">

2024-07-02 16:09 UTC, fvarg00 approved these changes

2024-07-04 03:54 UTC, anoop2811 approved these changes

2024-07-04 03:54 UTC, merged