Chore: Update project README and add LICENSE
Guidewire/fern-ui pull request #9
Opened 2024-07-08 05:12 UTC by gowtham-ra

- Update README with project description and setup instructions
- Add LICENSE file for the project

2024-07-12 03:24 UTC, anoop2811 approved these changes

2024-07-12 03:27 UTC, anoop2811 requested changes
README.md instead of README.MD

2024-07-12 03:33 UTC, gowtham-ra commented on README.MD
Thank you for catching that. I've updated it now

2024-07-17 04:14 UTC, tedd-E approved these changes

2024-07-17 05:36 UTC, anoop2811 approved these changes

2024-07-17 05:36 UTC, merged